#ifndef _iBOMBER_H_
#define _iBOMBER_H_
BOOL WINAPI CtrlHandler(DWORD);
int APIENTRY WinMain(HINSTANCE,HINSTANCE,LPSTR,int);
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcConsole(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcGameOptions(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcCfgName(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcConfigs(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcSkins(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcMaps(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcPressKey(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcTxtMsg(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcNoms(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcName(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcNameSession(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcSessions(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcProvider(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcNumPlayers(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcNumLocalPlayers(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcStart(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcOptions(HWND,UINT,WPARAM,LPARAM);
BOOL CALLBACK DlgProcControls(HWND,UINT,WPARAM,LPARAM);
//BOOL CALLBACK DlgProcScores(HWND,UINT,WPARAM,LPARAM);
#ifndef DX3
HRESULT WINAPI EnumsModesCallback(LPDDSURFACEDESC2 lpDDSurfaceDesc,
								  LPVOID lpContext);
#else
HRESULT WINAPI EnumsModesCallback(LPDDSURFACEDESC lpDDSurfaceDesc,
								  LPVOID lpContext);
#endif
BOOL FAR PASCAL EnumPlayersCallback(DPID,DWORD,LPCDPNAME,DWORD,LPVOID);
BOOL FAR PASCAL EnumCountRealPlayersCallback(DPID,DWORD,LPCDPNAME,DWORD,LPVOID);
BOOL FAR PASCAL DedicatedEnumConnectionsCallback(LPCGUID,LPVOID,DWORD,LPCDPNAME,DWORD,LPVOID);
BOOL FAR PASCAL DirectPlayEnumConnectionsCallback(LPCGUID,LPVOID,DWORD,LPCDPNAME,DWORD,LPVOID);
//BOOL CALLBACK DIEnumDeviceObjectsProc(LPCDIDEVICEOBJECTINSTANCE,LPVOID);

/*
extern "C" {
int __stdcall MICROTIMER(int);
int __stdcall LIRETIMER(int);
}
*/
#endif
