#ifndef _LSTRINGS_H_
#define _LSTRINGS_H_

#ifdef LANG_FR
#define LSZ_NOTEAM "Aucune Equipe"
#define LSZ_REDTEAM "Equipe Rouge"
#define LSZ_BLUETEAM "Equipe Bleue"
#define LSZ_NOTNUMP "Pas le même nombre de joueurs entre dwUser4 et GetRealNumPlayers"
#define LSZ_PAUSE "PAUSE"
#define LSZ_ldSECS "%ld secondes"
#define LSZ_ldSEC "%ld seconde"
#define LSZ_DEMO "Démonstration"
#define LSZ_EXECORRUPTED "Exécutable corrompu!"
#define LSZ_FATALERR "Erreur Fatale"
#define LSZ_NORDTSC "Instruction RDTSC non détéctée"
#define LSZ_REQU586 "Processeur Pentium® ou compatible requis."
#define LSZ_CANTINITFS "Impossible d'initialiser le système de fichiers (Probablement un fichier manquant)"
#define LSZ_INIT "Initialisation"
#define LSZ_DI_FAILED "CoCreateInstance(IDirectInput) a échoué"
#define LSZ_DI_INIT "Initialisation DirectInput"
#define LSZ_DI_CANTINIT "Echec de l'initialisation de l'interface DirectInput"
#define LSZ_DI_CANTCREATEKB "CreateDevice(Keyboard) a échoué"
#define LSZ_CANTENUMMODES "Impossible d'énumérer les modes vidéos"
#define LSZ_VMENUM "Enumération des modes graphiques"
#define LSZ_NOVM "Pas de modes graphiques énumérés"
#define LSZ_TOOMANYVM "Trop de modes vidéos à énumérer"
#define LSZ_DD_FAILED "CoCreateInstance(IDirectDraw) a échoué"
#define LSZ_DD_INIT "Initialisation DirectDraw"
#define LSZ_DD_CANTINIT "Echec de l'initialisation de l'interface DirectDraw"
#define LSZ_DD_CANTSETCOOP "DDSetCooperativeLevel a echoué"
#define LSZ_DD_UNSUPPVM "Mode vidéo non supporté"
#define LSZ_DD_CANTCREATESP "Impossible de créer la surface primaire"
#define LSZ_DD_CANTCREATESS "Impossible de créer la surface secondaire"
#define LSZ_DD_CANTCREATESPR "Impossible de créer la surface des sprites"
#define LSZ_DD_CANTCREATEBUFF "Impossible de créer la surface tampon"
#define LSZ_DD_CANTCREATECLIP "Impossible de créer le clipper"
#define LSZ_DD_CANTCREATESC "Impossible de créer la surface des scores"
#define LSZ_DD_CANTGETATTACHED "Impossible d'obtenir la surface attachée"
#define LSZ_DD_NOCC "Pas de DirectDrawColorControl"
#define LSZ_DD_CANTLOADSPR "Impossible de charger les sprites"
#define LSZ_ldWONWITHldPTS "%s a pris l'avantage avec %ld Points"
#define LSZ_ldWONWITHldPT "%s a pris l'avantage avec %ld Point"
#define LSZ_RUNFOR "Exécution pendant : %ld"
#define LSZ_ERRINsMAP "Erreur dans %s\\BMap.txt"
#define LSZ_ERRINDEFMAP "Erreur dans la carte par défaut"
#define LSZ_CANTOPENsMAP "Impossible d'ouvrir %s\\BMap.txt"
#define LSZ_CANTOPENDEFMAP "Impossible d'ouvrir la carte par défaut"
#define LSZ_sKILLEDs "%s a tué %s"
#define LSZ_sSUICIDE "%s s'est suicidé"
#define LSZ_NEWMAPs "Nouvelle carte: %s"
#define LSZ_OPTMENU "Menu des Options - "
#define LSZ_DEFAULT "Par Défaut"
#define LSZ_CON9k6 "Connexion très lente (<=9.6Kbps)"
#define LSZ_CON14k4 "Connexion lente (<=14.4Kbps)"
#define LSZ_CON33k6 "Connexion standard (<=33.6Kbps)"
#define LSZ_CON1m "Connexion rapide (<=1Mbps)"
#define LSZ_CONmax "Connexion très rapide (>1Mbps)"
#define LSZ_LOCALGAME "Jouer en local"
#define LSZ_SESSLIST0 "%s: %ld joueurs (%ld max) et %ld spectateurs Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST1 "%s: %ld joueurs (%ld max) et %ld spectateur Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST2 "%s: %ld joueur (%ld max) et %ld spectateurs Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST3 "%s: %ld joueur (%ld max) et %ld spectateur Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST0nm "%s: %ld joueurs et %ld spectateurs Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST1nm "%s: %ld joueurs et %ld spectateur Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST2nm "%s: %ld joueur et %ld spectateurs Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST3nm "%s: %ld joueur et %ld spectateur Version %ld.%ld.%ld.%ld"
#define LSZ_SELSESSUPDATE "Choix d'une session-Mise à jour..."
#define LSZ_SELSESS "Choix d'une session"
#define LSZ_NOVICE "Novice"
#define LSZ_MEDIUM "Moyen"
#define LSZ_ADVANCED "Avancé"
#define LSZ_EXPERT "Expert"
#define LSZ_NEWCONFIG "Nouvelle Configuration"
#define LSZ_WAITMPRESET "Patientez SVP, Reset Multijoueurs ..."
#define LSZ_WAITRR "Attente de ResetReply ..."
#define LSZ_RRRECEIVED "ResetReply recu"
#define LSZ_SENDBLOCS "Envoi des blocs ..."
#define LSZ_SYNC "Synchronisation ..."
#define LSZ_SYNC1 "Synchronisation 1 ..."
#define LSZ_SYNC2 "Synchronisation 2 ..."
#define LSZ_WAITBLOCS "Attente des blocs ..."
#define LSZ_ONERECEIVE "Un joueur recoit un fichier ..."
#define LSZ_FILERECEIVE "Réception d'un fichier ..."
#define LSZ_COMPRESSs "Compression de %s ..."
#define LSZ_SENDsTOs "Envoi de %s à %s ..."
#define LSZ_NOWAV "Fichier son introuvable"
#define LSZ_ERROR "Erreur"
#define LSZ_SCAFTERdHdMdS "Scores après %ldh %ldmin %lds"
#define LSZ_SCAFTERdMdS "Scores après %ldmin %lds"
#define LSZ_SCAFTERdS "Scores après %lds"
#define LSZ_dVICTIMES "%ld Victimes\n"
#define LSZ_ANDdAK "Et %ld Suicides\n\n"
#define LSZ_ERRSCFILE "Fichier des scores erroné.\nLe supprimer ?"
#define LSZ_SCORES "Scores"
#define LSZ_SCENTITLE "N:JOUEUR\tPOINTS\tPARTIES VICTIMES SUICIDES\n"
#define LSZ_BESTPSCORES "Meilleurs Scores (aux Points)"
#define LSZ_BESTRSCORES "Meilleurs Scores (au Rendement)"
#define LSZ_DELSCF "Supprimer le fichier des scores ?"
#define LSZ_NOSAVEDSCORES "Pas de Scores Enregistrés !"
#define LSZ_NOF1MSG "Pas de Message F1"
#define LSZ_NOF2MSG "Pas de Message F2"
#define LSZ_NOF3MSG "Pas de Message F3"
#define LSZ_NOF4MSG "Pas de Message F4"
#define LSZ_NOF5MSG "Pas de Message F5"
#define LSZ_NOF6MSG "Pas de Message F6"
#define LSZ_NOF7MSG "Pas de Message F7"
#define LSZ_NOF8MSG "Pas de Message F8"
#define LSZ_NAME1 "Joueur 1"
#define LSZ_NAME2 "Joueur 2"
#define LSZ_NAME3 "Joueur 3"
#define LSZ_NAME4 "Joueur 4"
#define LSZ_DX6ORH "DirectX 6.0 ou superieur non installé.\nVoulez-vous tout de même démarrer ?"
#define LSZ_DX3ORH "DirectX 3.0 ou superieur non installé.\nVoulez-vous tout de même démarrer ?"
#define LSZ_ATTENTION "Attention!"
#define LSZ_UNKNOWN_DXVER "Version de DirectX inconnue"
#define LSZ_UNKNOWN_WIN "Version de Windows inconnue"
#define LSZ_KEYd "Touche #%ld"
//Multi.cpp
#define LSZ_DP_INIT "Initialisation Multijoueurs"
#define LSZ_DP_NOSP "Le fournisseur d'accès requis n'est pas présent"
#define LSZ_DP_CANTINIT "Impossible d'initialiser l'interface DirectPlay"
#define LSZ_DP_CANTCREATEDP "Impossible de créer l'interface DirectPlay"
#define LSZ_DP_CANTJOIN "Impossible de joindre la session"
#define LSZ_DP_CANTRETINFO "Impossible d'obtenir les informations sur la session"
#define LSZ_DP_BADVER "Incompatibilité de versions"
#define LSZ_DP_BADPROTO "Protocole incorrect"
#define LSZ_DP_FREEZEDSESSION "Session bloquée à la réinitialisation"
#define LSZ_DP_IA " (IA)"
#define LSZ_DP_CANTENUMSESSIONS "Impossible d'enumérer les sessions"
#define LSZ_DP_CANTCREATEPLAYER "Impossible de créer un joueur"
#define LSZ_DP_CANTCREATESPECT "Impossible de créer un joueur spectateur"
#define LSZ_DP_CANTENUMPLAYERS "Impossible d'énumérer les joueurs"
#define LSZ_DP_BADPLNB "Nombre de joueurs erroné"
#define LSZ_DP_ldPLAYERldSPECT "%ld joueurs dans la session dont %ld spectateurs"
#define LSZ_DP_CANTRETPLINFO "Impossible d'obtenir les infosrmations d'un joueur"
#define LSZ_DP_CANTCREATE "Impossible de créer la session"
#define LSZ_DP_IANAME1 "Joueur 1 (IA)"
#define LSZ_DP_IANAME2 "Joueur 2 (IA)"
#define LSZ_DP_IANAME3 "Joueur 3 (IA)"
#define LSZ_DP_IANAME4 "Joueur 4 (IA)"
#define LSZ_DP_CANTINITCONN "Initialisation de la connection impossible"
#define LSZ_DP_CANTCONNECTLOBBY "Lobby: Impossible de se connecter"
#define LSZ_DP_sDED "%s (Dédié)"
#define LSZ_DP_sMULTICAST "%s (Multicast)"

#define LSZ_DP_PING_NOPLAYERS "PING: Aucun joueurs"
#define LSZ_DED_HELP "Ctrl+Alt+O: Affiche/cache la console\r\nCtrl+Alt+Q: Equivalent à la commande QUIT ou CLOSE"
#define LSZ_DED_HELPCMDLST "Commandes: QUIT/CLOSE/PING/STATS/HIDE/MINIMIZE/HELP"
#define LSZ_DED_SESSIONSTATS "Statistiques de la session:"
#define LSZ_DED_NUMPLAYERS "Nombre de joueurs: %ld"
#define LSZ_DED_SESSIONNAME "Nom de la session: %s"
#define LSZ_DED_UNKNOWNCMD "Commande inconnue"

#define LSZ_DED_TITLE "Serveur dédié Bomber - %s"
#define LSZ_DED_STARTED "Serveur dédié démarré"
#define LSZ_DED_DPPROTOON "Protocole DirectPlay utilisé"
#define LSZ_DED_DPPROTOOFF "Protocole DirectPlay non utilisé"
#define LSZ_DED_STOPPING "Fermetture du serveur ..."
#define LSZ_DP_MPMODE "Mode Multijoueurs"
#define LSZ_DP_SDESCCHANGED "SessionDesc a changé"
#define LSZ_DP_ALLPLOUT "Tous les joueurs ont quitté la session !"
#define LSZ_DP_CANTDELPLAYER "Impossible de supprimer votre joueur de la session"
#define LSZ_DP_CANTRECREATEPL "Impossible de recréer votre joueur"
#define LSZ_DP_SUCCESSRECON "Reconnexion réussie"
#define LSZ_DP_NEWHOST "Vous êtes le nouvel hôte de cette session"
#define LSZ_DP_CANTFINDPL "Joueur introuvable"
#define LSZ_DP_NEWPLAYERd "Nouveau joueur %ld"
#define LSZ_DP_sENTERED "%s est entré dans la partie"
#define LSZ_DP_sGOESWdANDd "%s est parti avec %ld Victimes et %ld Suicides"
#define LSZ_DP_SPECTATORQUIT "Un spectateur a quitté la partie"
#define LSZ_DP_BLdON300 "Envoi du bloc %ld/300"
#define LSZ_DP_UNKNOWN_IDFROM "Joueur idFrom inconnu (Serveur dédié?)"
#define LSZ_DP_RECVALLBLOCS "Réception de tous les blocs"
#define LSZ_DP_RECVBLOCdON300 "Réception du bloc %ld/300"
#define LSZ_DP_SPECTENTER "Un spectateur est entré dans la session"
#define LSZ_DP_EJECTED "Vous avez été déconnecté de la session"
#define LSZ_DP_HOSTQUIT "L'hôte a quitté, reconnexion en cours ..."
//Son.cpp
#define LSZ_DS_FAILED "CoCreateInstance(IDirectSound) a échoué"
#define LSZ_DS_INIT "Initialisation DirectSound"
#define LSZ_DS_CANTINIT "Echec de l'initialisation de l'interface DirectSound"
#define LSZ_DS_CANTSETCOOP "DSSetCooperativeLevel a echoué"
#define LSZ_DS_CANTCREATEBP "Impossible de créer le buffer primaire"
#define LSZ_DS_CANTCREATEBS "Impossible de créer un buffer secondaire"
#define LSZ_DS_CANTLOCK "Lock du buffer son échoué"
#define LSZ_DS_NOTENOUGHBUFF "Pas assez de buffers sons"
//Voice.cpp
#define LSZ_DSC_FAILED "CoCreateInstance(IDirectSoundCapture) a échoué"
#define LSZ_DSC_INIT "Initialisation DirectSoundCapture"
#define LSZ_DSC_CANTINIT "Echec de l'initialisation de l'interface DirectSoundCapture"
#define LSZ_DSC_CANTCREATEDSCB "Impossible de créer le buffer d'enregistrement"

#elif defined LANG_EN

#define LSZ_NOTEAM "No Team"
#define LSZ_REDTEAM "Red Team"
#define LSZ_BLUETEAM "Blue Team"
#define LSZ_NOTNUMP "Not as players in dwUser4 as in GetRealNumPlayers"
#define LSZ_PAUSE "PAUSED"
#define LSZ_ldSECS "%ld seconds"
#define LSZ_ldSEC "%ld second"
#define LSZ_DEMO "Demonstration"
#define LSZ_EXECORRUPTED "Corrupted executable!"
#define LSZ_FATALERR "Fatal Error"
#define LSZ_NORDTSC "RDTSC instruction not detected"
#define LSZ_REQU586 "Pentium® or compatible processor required."
#define LSZ_CANTINITFS "Unable to initialize file system (Probably a missing file)"
#define LSZ_INIT "Initialization"
#define LSZ_DI_FAILED "CoCreateInstance(IDirectInput) failed"
#define LSZ_DI_INIT "DirectInput initialization"
#define LSZ_DI_CANTINIT "DirectInput interface initialization failure"
#define LSZ_DI_CANTCREATEKB "CreateDevice(Keyboard) failed"
#define LSZ_CANTENUMMODES "unable to enumerate video modes"
#define LSZ_VMENUM "Video modes enumeration"
#define LSZ_NOVM "No enumerated video modes"
#define LSZ_TOOMANYVM "Too many enumerated video modes"
#define LSZ_DD_FAILED "CoCreateInstance(IDirectDraw) failed"
#define LSZ_DD_INIT "DirectDraw initialization "
#define LSZ_DD_CANTINIT "DirectDraw interface initialization failure"
#define LSZ_DD_CANTSETCOOP "DDSetCooperativeLevel failed"
#define LSZ_DD_UNSUPPVM "Unsupported video mode"
#define LSZ_DD_CANTCREATESP "Unable to create primary surface"
#define LSZ_DD_CANTCREATESS "Unable to create secondary surface"
#define LSZ_DD_CANTCREATESPR "Unable to create sprites' surface"
#define LSZ_DD_CANTCREATEBUFF "Unable to create buffer surface"
#define LSZ_DD_CANTCREATECLIP "Unable to create clipper"
#define LSZ_DD_CANTCREATESC "Unable to create scores' surface"
#define LSZ_DD_CANTGETATTACHED "Unable to retrieve attached surface"
#define LSZ_DD_NOCC "No DirectDrawColorControl"
#define LSZ_DD_CANTLOADSPR "Unable to load sprites"
#define LSZ_ldWONWITHldPTS "%s has the advantage with %ld Points"
#define LSZ_ldWONWITHldPT "%s has the advantage with %ld Point"
#define LSZ_RUNFOR "Have been running for : %ld"
#define LSZ_ERRINsMAP "Error in %s\\BMap.txt"
#define LSZ_ERRINDEFMAP "Error in default map"
#define LSZ_CANTOPENsMAP "Unable to open %s\\BMap.txt"
#define LSZ_CANTOPENDEFMAP "Unable to open default map"
#define LSZ_sKILLEDs "%s killed %s"
#define LSZ_sSUICIDE "%s killed himself"
#define LSZ_NEWMAPs "New map: %s"
#define LSZ_OPTMENU "Options Menu - "
#define LSZ_DEFAULT "Default"
#define LSZ_CON9k6 "Very slow connexion (<=9.6Kbps)"
#define LSZ_CON14k4 "Slow connexion (<=14.4Kbps)"
#define LSZ_CON33k6 "Standard connexion (<=33.6Kbps)"
#define LSZ_CON1m "Fast connexion (<=1Mbps)"
#define LSZ_CONmax "Very fast connexion (>1Mbps)"
#define LSZ_LOCALGAME "Local game"
#define LSZ_SESSLIST0 "%s: %ld players (%ld max) with %ld spectators Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST1 "%s: %ld players (%ld max) with %ld spectator Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST2 "%s: %ld player (%ld max) with %ld spectators Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST3 "%s: %ld player (%ld max) with %ld spectator Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST0nm "%s: %ld players with %ld spectators Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST1nm "%s: %ld players with %ld spectator Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST2nm "%s: %ld player with %ld spectators Version %ld.%ld.%ld.%ld"
#define LSZ_SESSLIST3nm "%s: %ld player with %ld spectator Version %ld.%ld.%ld.%ld"
#define LSZ_SELSESSUPDATE "Session selection-Updating..."
#define LSZ_SELSESS "Session selection"
#define LSZ_NOVICE "Rookie"
#define LSZ_MEDIUM "Medium"
#define LSZ_ADVANCED "Advanced"
#define LSZ_EXPERT "Expert"
#define LSZ_NEWCONFIG "New Configuration"
#define LSZ_WAITMPRESET "Please Wait, Multiplayer reset ..."
#define LSZ_WAITRR "Waiting ResetReply ..."
#define LSZ_RRRECEIVED "ResetReply received"
#define LSZ_SENDBLOCS "Sendiong blocks ..."
#define LSZ_SYNC "Synchronization ..."
#define LSZ_SYNC1 "Synchronization 1 ..."
#define LSZ_SYNC2 "Synchronization 2 ..."
#define LSZ_WAITBLOCS "Waiting blocks ..."
#define LSZ_ONERECEIVE "One player is receiving a file ..."
#define LSZ_FILERECEIVE "Receiving a file ..."
#define LSZ_COMPRESSs "Compressing %s ..."
#define LSZ_SENDsTOs "Sending %s to %s ..."
#define LSZ_NOWAV "Can't find sound file"
#define LSZ_ERROR "Error"
#define LSZ_SCAFTERdHdMdS "Scoring after %ldh %ldmin %lds"
#define LSZ_SCAFTERdMdS "Scoring after %ldmin %lds"
#define LSZ_SCAFTERdS "Scoring after %lds"
#define LSZ_dVICTIMES "%ld Victims\n"
#define LSZ_ANDdAK "And %ld Autokills\n\n"
#define LSZ_ERRSCFILE "Mistaken scoring file.\nDelete ?"
#define LSZ_SCORES "Scoring"
#define LSZ_SCENTITLE "N:PLAYER\tPOINTS\tGAMES  VICTIMS AUTOKILLS\n"
#define LSZ_BESTPSCORES "Best Scores (regarding Points)"
#define LSZ_BESTRSCORES "Best Scores (regarding Accuracy)"
#define LSZ_DELSCF "Delete score file ?"
#define LSZ_NOSAVEDSCORES "No Saved Scores !"
#define LSZ_NOF1MSG "No F1 Message"
#define LSZ_NOF2MSG "No F2 Message"
#define LSZ_NOF3MSG "No F3 Message"
#define LSZ_NOF4MSG "No F4 Message"
#define LSZ_NOF5MSG "No F5 Message"
#define LSZ_NOF6MSG "No F6 Message"
#define LSZ_NOF7MSG "No F7 Message"
#define LSZ_NOF8MSG "No F8 Message"
#define LSZ_NAME1 "Player 1"
#define LSZ_NAME2 "Player 2"
#define LSZ_NAME3 "Player 3"
#define LSZ_NAME4 "Player 4"
#define LSZ_DX6ORH "DirectX 6.0 or greater not installed.\nStill try to start ?"
#define LSZ_DX3ORH "DirectX 3.0 or greater not installed.\nStill try to start ?"
#define LSZ_ATTENTION "Attention!"
#define LSZ_UNKNOWN_DXVER "Version de DirectX inconnue"
#define LSZ_UNKNOWN_WIN "Version de Windows inconnue"
#define LSZ_KEYd "Key #%ld"
//Multi.cpp
#define LSZ_DP_INIT "Multiplayer initialization"
#define LSZ_DP_NOSP "The required service provider is not present"
#define LSZ_DP_CANTINIT "Unable to initialize DirectPlay interface"
#define LSZ_DP_CANTCREATEDP "Unable to create DirectPlay interface"
#define LSZ_DP_CANTJOIN "Unable to join the session"
#define LSZ_DP_CANTRETINFO "Unable to obtain informations on the session"
#define LSZ_DP_BADVER "Non-compatibles versions"
#define LSZ_DP_BADPROTO "Bad protocol"
#define LSZ_DP_FREEZEDSESSION "Session freezed in reinitialization state"
#define LSZ_DP_IA " (AI)"
#define LSZ_DP_CANTENUMSESSIONS "Unable to enumerate sessions"
#define LSZ_DP_CANTCREATEPLAYER "Unable to create a player"
#define LSZ_DP_CANTCREATESPECT "Unable to create a spectator player"
#define LSZ_DP_CANTENUMPLAYERS "Unable to enumerate players"
#define LSZ_DP_BADPLNB "Bad players number"
#define LSZ_DP_ldPLAYERldSPECT "%ld players in the session, %ld are spectators"
#define LSZ_DP_CANTRETPLINFO "Unable to obtain player's informations"
#define LSZ_DP_CANTCREATE "Unable to create the session"
#define LSZ_DP_IANAME1 "Player 1 (AI)"
#define LSZ_DP_IANAME2 "Player 2 (AI)"
#define LSZ_DP_IANAME3 "Player 3 (AI)"
#define LSZ_DP_IANAME4 "Player 4 (AI)"
#define LSZ_DP_CANTINITCONN "Unable to initialize connection"
#define LSZ_DP_CANTCONNECTLOBBY "Lobby: Unable to connect"
#define LSZ_DP_sDED "%s (Dedicated)"
#define LSZ_DP_sMULTICAST "%s (Multicast)"

#define LSZ_DP_PING_NOPLAYERS "PING: No players"
#define LSZ_DED_HELP "Ctrl+Alt+O: Show/Hide the console\r\nCtrl+Alt+Q: Equivalent to the QUIT command"
#define LSZ_DED_HELPCMDLST "Commands: QUIT/CLOSE/PING/STATS/HIDE/MINIMIZE/HELP"
#define LSZ_DED_SESSIONSTATS "Session statistics:"
#define LSZ_DED_NUMPLAYERS "Players number: %ld"
#define LSZ_DED_SESSIONNAME "Session name: %s"
#define LSZ_DED_UNKNOWNCMD "Unknown command"

#define LSZ_DED_TITLE "Bomber dedicated server - %s"
#define LSZ_DED_STARTED "Dedicated server started"
#define LSZ_DED_DPPROTOON "DirectPlay protocol used"
#define LSZ_DED_DPPROTOOFF "DirectPlay protocol not used"
#define LSZ_DED_STOPPING "Server shutting down ..."
#define LSZ_DP_MPMODE "Multiplayers mode"
#define LSZ_DP_SDESCCHANGED "SessionDesc changed"
#define LSZ_DP_ALLPLOUT "All players exited the session !"
#define LSZ_DP_CANTDELPLAYER "Unable to delete your player from the session"
#define LSZ_DP_CANTRECREATEPL "Unable to recreate your player"
#define LSZ_DP_SUCCESSRECON "Successful reconnection"
#define LSZ_DP_NEWHOST "You are the new host of this session"
#define LSZ_DP_CANTFINDPL "Player not found"
#define LSZ_DP_NEWPLAYERd "New player %ld"
#define LSZ_DP_sENTERED "%s entered the game"
#define LSZ_DP_sGOESWdANDd "%s exited with %ld Victims and %ld Autokills"
#define LSZ_DP_SPECTATORQUIT "A spectator exited"
#define LSZ_DP_BLdON300 "Sending block %ld/300"
#define LSZ_DP_UNKNOWN_IDFROM "Unknown idFrom player (Dedicated server?)"
#define LSZ_DP_RECVALLBLOCS "Receiving all blocks"
#define LSZ_DP_RECVBLOCdON300 "Receiving block %ld/300"
#define LSZ_DP_SPECTENTER "A spectator entered the session"
#define LSZ_DP_EJECTED "You have been deconnected from the session"
#define LSZ_DP_HOSTQUIT "Host has exited, reconnecting ..."
//Son.cpp
#define LSZ_DS_FAILED "CoCreateInstance(IDirectSound) failed"
#define LSZ_DS_INIT "DirectSound initialization "
#define LSZ_DS_CANTINIT "DirectSound interface initialization failure"
#define LSZ_DS_CANTSETCOOP "DSSetCooperativeLevel failed"
#define LSZ_DS_CANTCREATEBP "Unable to create primary buffer"
#define LSZ_DS_CANTCREATEBS "Unable to create a secondary buffer"
#define LSZ_DS_CANTLOCK "Sound buffer lock failed"
#define LSZ_DS_NOTENOUGHBUFF "Not enough sound buffers"
//Voice.cpp
#define LSZ_DSC_FAILED "CoCreateInstance(IDirectSoundCapture) failed"
#define LSZ_DSC_INIT "DirectSoundCapture initialization"
#define LSZ_DSC_CANTINIT "DirectSoundCapture interface initialization failure"
#define LSZ_DSC_CANTCREATEDSCB "Unable to create the recording buffer"
#endif
#endif
