//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Bomber.rc
//
#define IDB_RESETCTRL                   3
#define IDB_DELCFG                      4
#define IDB_RESETGO                     5
#define IDB_RESETTM                     6
#define IDB_OPTIONS                     7
#define IDB_NEWCFG                      8
#define IDB_REFRESH                     9
#define IDB_SCORES                      10
#define IDB_TXTMSG                      11
#define IDB_RESET                       12
#define IDB_CONTROLS                    13
#define IDB_SKINS                       14
#define IDB_CFGMGR                      15
#define IDB_GAMEOPT                     16
#define IDB_MAPSELECT                   17
#define IDD_CFGNAME                     102
#define IDD_CONFIGS                     103
#define IDD_CONTROLS                    104
#define IDD_GAMEOPT                     105
#define IDD_MAPS                        106
#define IDD_NAMESESSION                 107
#define IDD_NOMS                        108
#define IDD_NUMLOCALPLAYERS             109
#define IDD_NUMPLAYERS                  110
#define IDD_OPTIONS                     111
#define IDD_PRESSKEY                    112
#define IDD_PROVIDER                    113
#define IDD_SESSIONS                    114
#define IDD_SKINS                       115
#define IDD_START                       116
#define IDD_TXTMSG                      117
#define IDD_WAITSESSION                 118
#define IDD_WAITSPLAYING                119
#define IDBMP_LOGO                      120
#define IDD_CONSOLE                     121
#define IDI_ICON_MARBLE                 122
#define IDI_ICON_BOMBER                 123
#define IDC_SCORES                      1001
#define IDC_TWO                         1002
#define IDC_THREE                       1003
#define IDC_FOUR                        1004
#define IDC_SPCOMBO                     1005
#define IDC_DEPTH                       1006
#define IDC_RADIO1                      1007
#define IDC_RADIO2                      1008
#define IDC_SESSIONLIST                 1009
#define IDC_NET_TOUT                    1010
#define IDC_NICKNAME                    1011
#define IDC_NOM1                        1012
#define IDC_NOM2                        1013
#define IDC_SESSIONNAME                 1014
#define IDC_NOM3                        1015
#define IDC_DINPUT                      1016
#define IDC_NOM4                        1017
#define IDC_DPPROTO                     1018
#define IDC_DBGMODE                     1019
#define IDC_TBUFFER                     1020
#define IDC_DUPSBUFF                    1021
#define IDC_SPRVIDEO                    1022
#define IDC_F1TXT                       1023
#define IDC_F2TXT                       1024
#define IDC_F3TXT                       1025
#define IDC_F4TXT                       1026
#define IDC_F5TXT                       1027
#define IDC_F6TXT                       1028
#define IDC_F7TXT                       1029
#define IDC_F8TXT                       1030
#define IDC_MIGRATEHOST                 1031
#define IDC_ENABLESON                   1032
#define IDC_ASYNCENUM                   1033
#define IDC_HISOUND                     1034
#define IDC_VSYNC                       1035
#define IDC_ENUMEVERY                   1036
#define IDC_TEVERY                      1037
#define IDC_CTRL1                       1038
#define IDC_VOICE                       1038
#define IDC_CTRL2                       1039
#define IDC_CTRL3                       1040
#define IDC_CTRL4                       1041
#define IDB_UP                          1042
#define IDB_DOWN                        1043
#define IDB_LEFT                        1044
#define IDB_RIGHT                       1045
#define IDB_FIRE1                       1046
#define IDB_FIRE2                       1047
#define IDB_FIRE3                       1048
#define IDC_UPLBL                       1049
#define IDC_DOWNLBL                     1050
#define IDC_LEFTLBL                     1051
#define IDC_RIGHTLBL                    1052
#define IDC_FIRE1LBL                    1053
#define IDC_FIRE2LBL                    1054
#define IDC_FIRE3LBL                    1055
#define IDC_SKINLIST                    1056
#define IDC_VOLSLIDER                   1057
#define IDC_BRIGHTSLIDER                1058
#define IDC_CONTRASTSLIDER              1059
#define IDC_SCROLLBAR1                  1060
#define IDC_BRIGHTLBL                   1061
#define IDC_CONTRASTLBL                 1062
#define IDC_LOGIN                       1063
#define IDC_CFGLIST                     1064
#define IDC_CFGNAME                     1065
#define IDC_BONUS0                      1066
#define IDC_BONUS3                      1067
#define IDC_BONUS4                      1068
#define IDC_BONUS5                      1069
#define IDC_BONUS6                      1070
#define IDC_BONUS7                      1071
#define IDC_BONUS8                      1072
#define IDC_BONUS9                      1073
#define IDC_BONUS10                     1074
#define IDC_BONUS11                     1075
#define IDC_BONUS12                     1076
#define IDC_BONUS14                     1077
#define IDC_BONUS15                     1078
#define IDC_BONUS16                     1079
#define IDC_SIMULBOMB                   1080
#define IDC_BLOC_COND                   1081
#define IDC_NBBOMB                      1082
#define IDC_NBBLAST                     1083
#define IDC_NBMINE                      1084
#define IDC_MORTPNT                     1085
#define IDC_AKPNT                       1086
#define IDC_RETNUCL                     1087
#define IDC_DISPRETNUCL                 1088
#define IDC_TELSVR                      1089
#define IDC_REV_TOUT                    1090
#define IDC_TELCLNT                     1091
#define IDC_MCH_TOUT                    1092
#define IDC_LOADSKIN                    1093
#define IDC_CANREV                      1094
#define IDC_FILE_BLOCK_SIZE             1095
#define IDC_SDDEATH_TOUT                1096
#define IDC_SHOWPING                    1097
#define IDC_SPECTATOR                   1098
#define IDC_ALLOWSPECTATORS             1099
#define IDC_ONELOCAL                    1100
#define IDC_GROUPMSG                    1101
#define IDC_TWOLOCAL                    1102
#define IDC_THREELOCAL                  1103
#define IDC_FOURLOCAL                   1104
#define IDC_IA1                         1105
#define IDC_IA2                         1106
#define IDC_IA3                         1107
#define IDC_IA4                         1108
#define IDC_SAVESCORES                  1109
#define IDC_BOTLEVEL                    1110
#define IDC_MAPLIST                     1111
#define IDC_MAPDELAY                    1112
#define IDC_TEAM1                       1113
#define IDC_TEAM2                       1114
#define IDC_TEAM3                       1115
#define IDC_TEAM4                       1116
#define IDC_BOMBTCOLOR                  1117
#define IDC_PLAYERTCOLOR                1118
#define IDC_MAPPREVIEW                  1119
#define IDC_DEDICATED                   1120
#define IDC_RDEDICATED                  1121
#define IDC_RMULTICAST                  1122
#define IDC_RNORMAL                     1123
#define IDC_LOGO                        1124
#define IDB_WEBSITE                     1125
#define IDC_CONOUT                      1126
#define IDC_CONIN                       1128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
